### ISSUE TITLE
confidence

### ISSUE THREAD

**Issue by hopeldy** [dpressel/nbsvm-xl#1]
How do I get the confidence that a sample belongs to a category

**Comment by dpressel** [comment]
Both of the algos implemented for NBSVM-XL (LR AKA LogLoss and SVM AKA HingeLoss) return back a number centered at 0 (default is SVM).

SVM is not a probabilistic model.  See here for more explanation:

https://stats.stackexchange.com/questions/14876/interpreting-distance-from-hyperplane-in-svm

If you are using LR instead of SVM (pass --loss log), you should be able to convert back to a probability -- the _classify_ function yields the log odds (or logit), which you can convert back to a probability:


```java
  public static double logOddsToProb(double logOdds)
  {
        double odds = Math.pow(Math.E, logOdds);
        return odds / (odds + 1.0);
  }
```
